font_family Fira Code
bold_font Fira Code
italic_font Fira Code
bold_italic_font Fira Code
font_size 12.0

# Catppuccin Mocha 主题
include themes/catppuccin-mocha.conf

# 关掉没用的视觉效果省性能
background_opacity 1.0
dynamic_background_opacity no
cursor_blink_interval 0

# 键盘
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

# 滚动
scrollback_lines 10000
