# Profiles Config for Clash Verge

current: rzPvZKyEewov
chain: null
valid: null
items:
- uid: rMbL4aGa2hlt
  type: remote
  name: 宏远的翻墙
  file: rMbL4aGa2hlt.yaml
  desc: ''
  url: https://mojie0201.xn--8stx8olrwkucjq3b.com/api/v1/client/subscribe?token=7eb3fdc461a5851cb3e7e5cebd335481
  extra:
    upload: 1096333338
    download: 36453726118
    total: 139586437120
    expire: 0
  updated: 1713280474
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 1440
- uid: rzPvZKyEewov
  type: remote
  name: 青蒿的翻墙
  file: rzPvZKyEewov.yaml
  desc: ''
  url: https://sub.djmyy.top/link/XeUVQqM7VSht65Q4?clash=1
  extra:
    upload: 3164730856
    download: 213854912476
    total: 825449512960
    expire: 1721373967
  updated: 1713280480
  option:
    with_proxy: false
    self_proxy: false
